layout_spectrum: 0.5780936311930418
favicon: null
name: ThunderbirdsAlumni
purpose: []
analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
cta:
  version: null
  bucket: null
  domain: null
color:
  brandStrength: 0.5
  lightness: 0.5016863
  saturation: 0.5084317
  rhythmicContrast: 0.4974705
  brandColors:
    - '#fcfbf6'
    - '#211310'
    - '#486082'
    - '#9ca3b5'
    - '#cb4a2b'
typography_spectrum: 1
