name: ThunderbirdsAlumni
favicon: null
layout_spectrum: 0.5780936311930418
typography_spectrum: 0.32165046501904726
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.48917685775086284
  lightness: 0.6247434851247817
  saturation: 0.0213783816434443
  rhythmicContrast: 0.806417261948809
purpose: []
