name: ThunderbirdsAlumni
favicon: null
layout_spectrum: 0.5780936311930418
typography_spectrum: 0.3216504650190473
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fcfbf6'
    - '#211310'
    - '#486082'
    - '#9ca3b5'
    - '#cb4a2b'
  brandStrength: 0.5
  lightness: 1
  saturation: 1
  rhythmicContrast: 0.806417261948809
purpose: []
