name: ThunderbirdsAlumni
favicon: null
layout_spectrum: 1
typography_spectrum: 1
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
title: THUNDERBIRDSALUMNI.COM      Once A Thunderbird Always A Thunderbird
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1d3565'
    - '#020202'
    - '#ebebeb'
    - '#860b06'
    - '#71809e'
  brandStrength: 0.5
  lightness: 0.5016863
  saturation: 0.5084317
  rhythmicContrast: 0.4974705
purpose: []
