color:
  brandStrength: 0.5
  saturation: 0.5084317
  brandColors:
    - '#ffffff'
    - '#424067'
    - '#858681'
    - '#d61204'
    - '#141227'
  lightness: 0.5016863
  rhythmicContrast: 0.4974705
title: ThunderbirdsAlumni.com
analytics:
  twitter: null
  google: null
  facebook: null
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
cta:
  version: null
  bucket: null
  domain: null
favicon: null
layout_spectrum: 1
purpose: []
name: ThunderbirdsAlumni.com
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 1
